### PR TITLE
Update to last 1.71

### PR DESCRIPTION
**Pull request by amerkoleci**
Update to last 1.71

### CODE REVIEW

**Comment by mellinoe** [comment]
@amerkoleci Thanks for doing this, and sorry for the delay. I'll be looking at this sometime soon.

**Comment by CorrM** [comment]
@mellinoe news .?

**Comment by mellinoe** [comment]
Sorry for the delay. Still hoping to get to this soon.

**Comment by mellinoe** [comment]
@amerkoleci Merged now, thanks!

**Comment by CorrM** [comment]
where Nuget will be ready .?

**Comment by amerkoleci** [comment]
Dude relax, I suppose the time that takes appveyor, you can use artifacts from there meanwhile

**Comment by CorrM** [comment]
what mean of relax i just ask when .? i not force u to do something !

**Comment by mellinoe** [comment]
Nuget package uploaded: https://www.nuget.org/packages/ImGui.NET/1.71.0

**Comment by CorrM** [comment]
@mellinoe ty ❤️ for your work.
there is a patch note .?

**Comment by mellinoe** [comment]
@CorrM Check the imgui repo for 1.71 patch notes. I'm not sure when I will update Veldrid.ImGui -- perhaps sometime in the next week or so.

**Pull request merged**
