### PR TITLE
Fix native dylib location on Mac

### PR DESCRIPTION
**Pull request by roeyskoe**
Currently ImGui.NET places native mac dylib to `runtimes/osx-universal`, which is not a valid location for DllImport to load it.
Imgui.NET 1.87.3 does not work with MacOs, without manually moving the `libcimgui.dylib` to a correct location.

This pr renames`osx-universal` to `osx`, which works with both Intel and Arm platforms.

See also accepted names for `runtimes` folders: https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.NETCore.Platforms/src/runtime.json

### CODE REVIEW

**Comment by vis2k** [comment]
this currently blocks usage of IMGUI on apple silicon.
fix would be greatly appreciated :)

**Comment by frenzibyte** [comment]
So far, the `osx` RID has worked well on both Intel and Apple Silicon platforms, and can confirm that in the approach I noted at https://github.com/mellinoe/veldrid-spirv/pull/24. Gonna try testing this and see if it's working on `osx` as well.

**Comment by frenzibyte** [comment]
After testing in a similar manner to https://github.com/mellinoe/veldrid-spirv/pull/24, the `osx` RID also works here on M1, and `osx-arm64` is not required.

**Comment by roeyskoe** [comment]
Yes `osx` should work according to the runtime.json I linked, but it didn't on my machine (M1, Monterey 12.3.1, .NET 6.0.201). 

Please tell if just the first commit of this PR works on your machine, it was made with an Intel Mac.

**Comment by roeyskoe** [comment]
Good timing :P

But this raises a question, why did it not work when I tested?

**Comment by frenzibyte** [comment]
I would be curious about your way of testing it, can you fill in the steps? for me I just created a local nuget package and referenced it on a fresh project, and the `osx` RID is working there.

**Comment by roeyskoe** [comment]
That is exactly what I did. 
When it didn't work, I just copied the `libcimgui.dylib` to `osx-arm64` in the output directory and then it ran properly.

**Comment by frenzibyte** [comment]
As a sanity check, on a fresh console app project, can you reference [this package](https://www.nuget.org/packages/frenzi.Veldrid.SPIRV) and test with this code:
```csharp
// See https://aka.ms/new-console-template for more information

using Veldrid.SPIRV;

Veldrid.SPIRV.SpirvCompilation.CompileVertexFragment(Array.Empty<byte>(), Array.Empty<byte>(), CrossCompileTarget.MSL, new CrossCompileOptions());
```

and see if it finds the native library or not?

**Comment by roeyskoe** [comment]
It does.

But I figured out why `osx` did not work when I tested.

In the output folder there is `projectName.deps.json`. In my test project it had a reference to `runtimes/osx-universal/native/libcimgui.dylib`. Because of that, `osx` or `osx-universal` does not work, but `osx-arm64` does work. 

This does not really make sense in my mind...

**Comment by frenzibyte** [comment]
Well, I'm surprised as well, but at least it's discovered now. I think the latest changes can be reverted now and only keep the first one, yeah?

**Comment by roeyskoe** [comment]
Reverted and tested with fully clean project that it works. Its is possible that this may cause small issues with some users when updating, but I think that we can ignore that since clean output directory fixes this.

Thanks @frenzibyte :D

**Comment by sergey-tihon** [comment]
Should build script be updated as well?
1. https://github.com/mellinoe/ImGui.NET/blob/65e1442134347e8f9bb24be979de38474a7eda3f/download-native-deps.ps1#L18
2. https://github.com/mellinoe/ImGui.NET/blob/65e1442134347e8f9bb24be979de38474a7eda3f/download-native-deps.ps1#L63
3. https://github.com/mellinoe/ImGui.NET/blob/b196a86359a0d5d33fed32854fca470ea392e7dd/download-native-deps.sh#L28

**Pull request merged**
