### PR TITLE
Update to version 1.51 of cimgui/imgui.

### PR DESCRIPTION
**Pull request by dpethes**
This largely follows the breaking changes in release notes. It should cover all function renames, removals, parameter changes. Some function additions are covered as well: ColorPicker3/4, SetColorEditOptions, SetColumnWidth.
I also added a 64bit windows build of cimgui.

### CODE REVIEW

**Comment by mellinoe** [comment]
Hey @dpethes , thanks for the update! It looks like the PR is missing the `ColorEditFlags` and `Condition` enums. Did you forget to commit those new/renamed files?

**Comment by dpethes** [comment]
Sorry about that; amended. 
I was thinking about putting all enums/flags to one enum file - I thought we discussed it before but I couldn't find it, so it's most likely just my memory playing tricks on me. They are mostly small files, it would help me with orientation somewhat if I kept them together. What do you think?

**Comment by dpethes** [comment]
One additional thing: I usually do simple tests of the modified functions to check that the parameters are right, that the function name isn't misspelled etc. I think it would have some value if I kept it inside the sample window (or create another one):
* wider coverage of imgui's functions, so it would be easier to detect when something breaks with new imgui versions
* more imgui.net usage examples, where the usage of the translated version isn't obvious (some functions take strings with escape chars that are parsed in imgui/sprintf, like igText variants or Sliders, iirc)

Opinions?

**Comment by mellinoe** [comment]
Sorry for the delay on this -- I've been caught up with a lot of other stuff.

By the way, I plan on setting up some much better automation and testing for this in the near future, which should help me get changes in quicker when submitted.

**Comment by mellinoe** [comment]
I think there's a few new functions available that weren't added:

* `igPushStyleColorU32(ImGuiCol idx, ImU32 col);`
* `igGetColorU32*`
* `ImDrawList_GetClipRectMin`, `ImDrawList_GetClipRectMax`

We could always add those later.

Structure changes:
* There is a new field in `ImFontAtlas`, but I think this structure is not correct in the first place. The native `int` fields should be marshal'd as `Int32` in C#, not `IntPtr`. Don't worry about this one.

Looks good to me. I can probably build the other two versions soon-ish and publish a new version.

**Comment by dpethes** [comment]
Some sort of testing would be great, seems that Omar will be releasing new versions more often :)

I don't think I ever actually used ImFontAtlas/NativeFontAtlas directly, it may be broken for several versions.

**Pull request merged**
