### PR TITLE
fixes a bug with MonoGame and FNA when creating a texture at runtime

### PR DESCRIPTION
**Pull request by prime31**
fixes Mono not finding the dylib by prepending "lib"

### CODE REVIEW

**Comment by mellinoe** [comment]
I've thus far held off on this change, since I've long hoped that mono would align their native library search logic with .NET Core. Since that doesn't seem to be happening, I think it's fine to go ahead with this. However, I'd like to make the change over in https://github.com/mellinoe/ImGui.NET-nativebuild as well. Before that, the cimgui repo will probably need to get a PR to allow the "lib" prefix with some build flag.

**Comment by prime31** [comment]
Makes sense

**Comment by mikedJC** [comment]
How about something like this instead, so we can avoid having to rename the file altogether in the repo and upstream:

`<Content Include="$(RepositoryRootDirectory)/deps/cimgui/osx-x64/cimgui.dylib" Link="lib%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />`

**Comment by prime31** [comment]
How about something like this instead, so we can avoid having to rename the file altogether in the repo and upstream:

`<Content Include="$(RepositoryRootDirectory)/deps/cimgui/osx-x64/cimgui.dylib" Link="lib%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />`

**Comment by mellinoe** [comment]
@prime31 Sorry for the long delay on this one. I'd like to get this in soon and get a new release out.

As far as mono goes, I was under the impression that it would also need a DllMap file to work out of the box. All of the PInvokes in the library are to "cimgui", and I didn't think that mono was appending the "so" or "dylib" extension like .NET Core does. Is that the case, or is the DllMap unnecessary? I'd like to figure out whatever needs to be done to make the library work automatically on mono.

**Comment by prime31** [comment]
I've been using the solution from my [previous comment](https://github.com/mellinoe/ImGui.NET/pull/110#issuecomment-463296894) with both FNA and MonoGame backed by net471 and netcoreapp2.1 and it works perfectly on macOS. No DllMap necessary going that route.

**Comment by mellinoe** [comment]
@prime31 I merged this in along with a few other changes, namely updating to v1.68 of the native library (recently released). Note that I did revert the change that renamed cimgui.dylib on disk, so you should continue to use the "Link" workaround for the time being in your project file.

I also added a build target into the NuGet package will should be used automatically in mono C# projects. It should choose which native library to deploy based on the build configuration.

**Comment by mellinoe** [comment]
https://www.nuget.org/packages/ImGui.NET/1.68.0

**Comment by prime31** [comment]
Awesome! The link-and-rename is probably the better way to go anyway. Time to go make some text filters and merged fonts with the other updates!

**Pull request merged**
